spring:
  application:
    name: eureka-server
#spring:
  #cloud:
    #config:
      #uri=http://localhost:8888
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    #prefer-ip-address=true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
